import "unknwn.idl";
import "oaidl.idl";
import "ocidl.idl";

[object, uuid(9490e8d9-ca97-4ffe-81f1-c6d125479c1f)]
interface IServiceManager : IUnknown {
	HRESULT init();	
	HRESULT enumetateServiceNames([out,retval] SAFEARRAY(BSTR) *ppServices);
};